-- BlockView — listing analytics: views per listing, by date and by device.
-- Run in Supabase: SQL Editor -> New query -> paste -> Run. Safe to re-run.
--
-- PRIVACY BY DESIGN: a view row holds no IP, no user id and no user agent — only
-- a random per-browser key used to deduplicate. Agents never read raw rows (there
-- is deliberately NO select policy); they only get aggregates through the RPC.

-- ========================================================= listing_views ==
create table if not exists public.listing_views (
  id          bigint generated by default as identity primary key,
  listing_id  uuid not null references public.listings (id) on delete cascade,
  event       text not null check (event in ('impression','detail','contact','lead','share','favorite')),
  surface     text not null check (surface in ('web','app')),
  platform    text not null default 'other' check (platform in ('android','ios','desktop','other')),
  viewer_key  text not null check (char_length(viewer_key) between 8 and 64),
  day         date not null default current_date,
  created_at  timestamptz not null default now(),
  -- one row per viewer, per event, per listing, per day: this both deduplicates
  -- the numbers and acts as the flood limit (extra attempts simply conflict)
  unique (listing_id, event, viewer_key, day)
);
create index if not exists listing_views_listing_idx on public.listing_views (listing_id, day);
create index if not exists listing_views_day_idx     on public.listing_views (day);

-- ================================= server-side guard on every inserted row ==
-- Stops three things the client could otherwise do: back-date a view, count a
-- view on a listing that isn't public, and inflate its own listing's numbers.
create or replace function public.guard_listing_view()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  owner uuid;
  is_public boolean;
begin
  select l.agent_id, l.status = 'approved' into owner, is_public
  from public.listings l where l.id = new.listing_id;

  if owner is null or not is_public then
    return null;                      -- unknown or unapproved listing: drop silently
  end if;
  if auth.uid() is not null and auth.uid() = owner then
    return null;                      -- an agent viewing their own listing never counts
  end if;

  new.day := current_date;            -- always server time
  new.created_at := now();
  return new;
end; $$;

drop trigger if exists listing_views_guard on public.listing_views;
create trigger listing_views_guard before insert on public.listing_views
  for each row execute procedure public.guard_listing_view();

-- ============================================================ RLS =========
alter table public.listing_views enable row level security;

drop policy if exists listing_views_insert on public.listing_views;
drop policy if exists listing_views_admin  on public.listing_views;

-- anyone (signed in or not) may record a view; the trigger above vets it
create policy listing_views_insert on public.listing_views for insert with check (true);
-- NO select policy for agents on purpose: raw rows stay unreadable from the
-- browser. Admins can inspect if they ever need to.
create policy listing_views_admin on public.listing_views for select using (public.is_admin());

-- ================================================= aggregates for agents ==
-- The only way an agent sees their numbers. Returns aggregates only — never a
-- row that could identify a visitor.
create or replace function public.agent_listing_stats(
  from_date date,
  to_date   date,
  surface_filter text default null,      -- 'web' | 'app' | null = both
  listing   uuid default null            -- one listing, or null = all of mine
) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  admin boolean := public.is_admin();
  result jsonb;
begin
  if me is null then
    raise exception 'NOT_SIGNED_IN' using errcode = 'P0001';
  end if;
  if not admin and not public.is_agent() then
    raise exception 'FORBIDDEN' using errcode = 'P0001';
  end if;
  if from_date is null or to_date is null or to_date < from_date then
    raise exception 'BAD_RANGE' using errcode = 'P0001';
  end if;

  with scope as (
    select l.id, l.title, l.deal, l.status
    from   public.listings l
    where  (admin or l.agent_id = me)             -- an agent only ever sees their own
      and  (listing is null or l.id = listing)
  ),
  ev as (
    select v.*
    from   public.listing_views v
    join   scope s on s.id = v.listing_id
    where  v.day between from_date and to_date
      and  (surface_filter is null or v.surface = surface_filter)
  )
  select jsonb_build_object(
    'totals', (
      select jsonb_build_object(
        'impressions',    count(*) filter (where event = 'impression'),
        'views',          count(*) filter (where event = 'detail'),
        'unique_viewers', count(distinct viewer_key) filter (where event = 'detail'),
        'contacts',       count(*) filter (where event in ('contact','lead')),
        'shares',         count(*) filter (where event = 'share'),
        'favorites',      count(*) filter (where event = 'favorite'),
        'web',            count(*) filter (where event = 'detail' and surface = 'web'),
        'app',            count(*) filter (where event = 'detail' and surface = 'app')
      ) from ev
    ),
    'daily', coalesce((
      select jsonb_agg(d order by d->>'day')
      from (
        select jsonb_build_object(
          'day',   day,
          'views', count(*) filter (where event = 'detail'),
          'web',   count(*) filter (where event = 'detail' and surface = 'web'),
          'app',   count(*) filter (where event = 'detail' and surface = 'app')
        ) as d
        from ev group by day
      ) x
    ), '[]'::jsonb),
    'listings', coalesce((
      select jsonb_agg(r order by (r->>'views')::int desc)
      from (
        select jsonb_build_object(
          'id',             s.id,
          'title',          s.title,
          'status',         s.status,
          'views',          count(e.*) filter (where e.event = 'detail'),
          'unique_viewers', count(distinct e.viewer_key) filter (where e.event = 'detail'),
          'impressions',    count(e.*) filter (where e.event = 'impression'),
          'contacts',       count(e.*) filter (where e.event in ('contact','lead')),
          'web',            count(e.*) filter (where e.event = 'detail' and e.surface = 'web'),
          'app',            count(e.*) filter (where e.event = 'detail' and e.surface = 'app')
        ) as r
        from scope s left join ev e on e.listing_id = s.id
        group by s.id, s.title, s.status
      ) y
    ), '[]'::jsonb)
  ) into result;

  return result;
end; $$;

revoke all on function public.agent_listing_stats(date, date, text, uuid) from public, anon;
grant execute on function public.agent_listing_stats(date, date, text, uuid) to authenticated;

-- ======================================================= retention =======
-- Raw events older than 90 days add nothing once the numbers are read; drop them.
-- Run manually, or from a scheduled job if you enable pg_cron.
create or replace function public.purge_old_listing_views(keep_days int default 90)
returns int language plpgsql security definer set search_path = public as $$
declare removed int;
begin
  if not public.is_admin() then
    raise exception 'FORBIDDEN' using errcode = 'P0001';
  end if;
  delete from public.listing_views where day < current_date - keep_days;
  get diagnostics removed = row_count;
  return removed;
end; $$;

revoke all on function public.purge_old_listing_views(int) from public, anon;
grant execute on function public.purge_old_listing_views(int) to authenticated;

select count(*) as recorded_views from public.listing_views;
