-- BlockView — record what changed on a listing, and send edits back for approval.
-- Run in Supabase: SQL Editor -> New query -> paste -> Run. Safe to re-run.
--
-- Two problems this fixes:
--
-- 1. An approved listing could be edited freely. The price, the address or the
--    whole description could change after moderation and the listing stayed on
--    the map — the approval was for text nobody could see any more. A material
--    edit by a non-admin now drops it back to 'pending'.
--
-- 2. When it comes back, the admin had no idea what changed and had to re-read
--    the whole listing. Every edit is now recorded field by field.

-- ========================================================== revisions ====
create table if not exists public.listing_revisions (
  id            bigint generated by default as identity primary key,
  listing_id    uuid not null references public.listings (id) on delete cascade,
  changed_by    uuid references auth.users (id) on delete set null,
  by_admin      boolean not null default false,
  changes       jsonb  not null default '{}',   -- {field: {from: ..., to: ...}}
  status_before text,
  status_after  text,
  changed_at    timestamptz not null default now()
);
create index if not exists listing_revisions_listing_idx
  on public.listing_revisions (listing_id, changed_at desc);

-- ==================================================== the diff trigger ====
create or replace function public.track_listing_changes()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  -- only fields a buyer would care about; updated_at and photo rows are noise
  fields text[] := array[
    'title','description','price','rooms','size','floor','floors_total',
    'type','category','deal','age','furnished','pets','parking','elevator',
    'tour_url','website_url','building_id'
  ];
  f        text;
  o        jsonb := to_jsonb(old);
  n        jsonb := to_jsonb(new);
  diff     jsonb := '{}'::jsonb;
  material boolean := false;
  admin    boolean := coalesce(public.is_admin(), false);
begin
  foreach f in array fields loop
    if (o -> f) is distinct from (n -> f) then
      diff := diff || jsonb_build_object(f, jsonb_build_object('from', o -> f, 'to', n -> f));
      material := true;
    end if;
  end loop;

  -- a live listing that gets edited has to be looked at again. Admin edits are
  -- the moderation itself, so they don't bounce it back.
  if material and old.status = 'approved' and new.status = 'approved'
     and auth.uid() is not null and not admin then
    new.status := 'pending';
  end if;

  if material or (new.status is distinct from old.status) then
    insert into public.listing_revisions
      (listing_id, changed_by, by_admin, changes, status_before, status_after)
    values (new.id, auth.uid(), admin, diff, old.status, new.status);
  end if;

  return new;
end; $$;

-- runs after listings_status_guard (alphabetical), so the no-self-approval
-- rule is applied before this decides whether to bounce the listing back
drop trigger if exists listings_track_changes on public.listings;
create trigger listings_track_changes before update on public.listings
  for each row execute procedure public.track_listing_changes();

-- ============================================================== RLS ======
alter table public.listing_revisions enable row level security;

drop policy if exists listing_revisions_read on public.listing_revisions;
-- the admin moderating it, and the agent who owns the listing, may read the
-- history. Nobody writes it from the browser — only the trigger does.
create policy listing_revisions_read on public.listing_revisions for select using (
  public.is_admin()
  or exists (select 1 from public.listings l
             where l.id = listing_id and l.agent_id = auth.uid())
);

select count(*) as revisions_recorded from public.listing_revisions;
