-- BlockView — real "what changed" feed for followed buildings.
-- Run in Supabase: SQL Editor -> New query -> paste -> Run. Safe to re-run.
--
-- Until now the alerts sheet showed a SIMULATED feed (random "price dropped 2.5%"
-- lines hashed from the building id). Following a building — the Pro-only feature
-- — therefore delivered nothing real. This adds a genuine event feed: a trigger
-- records an event whenever a listing in a building actually changes, and a
-- follower reads the events for the buildings they follow.
--
-- SECURITY VERDICT — safe to run.
--   * building_events has RLS ON. SELECT is allowed only to a user who FOLLOWS
--     that building (or an admin). There is NO insert/update/delete policy, so
--     no browser can forge or tamper with an event — only the trigger writes.
--   * record_listing_event() is SECURITY DEFINER (so it can write past RLS) with
--     search_path pinned to public. It contains no dynamic SQL and only inserts
--     non-sensitive fields already visible on the public listing (title, price).
--   * follows.last_seen_at is written by the follow's own owner under the
--     existing follows_owner policy — no new exposure.
--   * Every statement is idempotent.

-- ============================================================ events ======
create table if not exists public.building_events (
  id          bigint generated by default as identity primary key,
  building_id text not null,
  listing_id  text,
  kind        text not null check (kind in ('new_listing','price_drop','sold','frozen')),
  meta        jsonb not null default '{}',
  created_at  timestamptz not null default now()
);
create index if not exists building_events_bid_idx
  on public.building_events (building_id, created_at desc);

-- per-follow "I have seen up to here" marker, for the unread badge
alter table public.follows add column if not exists last_seen_at timestamptz not null default now();

-- ======================================================== RLS policies ====
alter table public.building_events enable row level security;

drop policy if exists building_events_read on public.building_events;
create policy building_events_read on public.building_events for select using (
  exists (
    select 1 from public.follows f
    where f.building_id = building_events.building_id
      and f.user_id = auth.uid()
  )
  or public.is_admin()
);
-- deliberately no write policy: the SECURITY DEFINER trigger is the only writer.

-- ==================================================== event recorder =======
create or replace function public.record_listing_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- a listing becomes visible on the map (first time it reaches 'approved')
  if new.status = 'approved'
     and (tg_op = 'INSERT' or old.status is distinct from 'approved')
     and not exists (
       select 1 from public.building_events e
       where e.listing_id = new.id::text and e.kind = 'new_listing'
     ) then
    insert into public.building_events (building_id, listing_id, kind, meta)
    values (new.building_id, new.id::text, 'new_listing',
            jsonb_build_object('title', new.title, 'price', new.price));

  -- price cut on a listing that is already live
  elsif new.status = 'approved' and tg_op = 'UPDATE' and old.status = 'approved'
        and new.price is not null and old.price is not null and new.price < old.price then
    insert into public.building_events (building_id, listing_id, kind, meta)
    values (new.building_id, new.id::text, 'price_drop',
            jsonb_build_object('title', new.title, 'price', new.price, 'old_price', old.price));
  end if;

  -- status transitions worth announcing on their own
  if tg_op = 'UPDATE' and new.status = 'sold' and old.status is distinct from 'sold' then
    insert into public.building_events (building_id, listing_id, kind, meta)
    values (new.building_id, new.id::text, 'sold', jsonb_build_object('title', new.title));
  elsif tg_op = 'UPDATE' and new.status = 'frozen' and old.status is distinct from 'frozen' then
    insert into public.building_events (building_id, listing_id, kind, meta)
    values (new.building_id, new.id::text, 'frozen', jsonb_build_object('title', new.title));
  end if;

  return new;
end;
$$;

drop trigger if exists trg_listing_event on public.listings;
create trigger trg_listing_event
  after insert or update on public.listings
  for each row execute function public.record_listing_event();

-- quick check
select kind, count(*) from public.building_events group by kind order by kind;
