-- BlockView — subscription event log (feeds the daily report's Pro metrics).
-- Run in Supabase: SQL Editor -> New query -> paste -> Run. Safe to re-run.
-- Requires 43_revenuecat.sql.
--
-- Every RevenueCat webhook event is appended here by /api/revenuecat-webhook,
-- so the daily report can count "trials started yesterday" and
-- "trial -> paid conversions yesterday" — deltas that profiles.plan (a current
-- snapshot) cannot answer. RevenueCat stays the source of truth; this is just
-- our own durable copy of the events it already sends us.
--
-- SECURITY VERDICT — SAFE to run.
--   * New table only. No change to any existing table, policy, or privilege.
--   * RLS is ENABLED with NO policies, so no anon / authenticated / browser role
--     can read or write a single row. Only the service_role (the webhook, which
--     bypasses RLS) ever touches it — the subscriber stream and prices are never
--     exposed to a client. The daily report reads it with the same service key,
--     server-side, and only ever asks for counts.
--   * No SECURITY DEFINER function, no dynamic SQL, no destructive statement.
--   * event_id is UNIQUE, so RevenueCat's webhook retries cannot double-count.

create table if not exists public.subscription_events (
  id                  bigint generated by default as identity primary key,
  event_id            text unique,               -- RevenueCat event id (idempotency)
  type                text not null,             -- INITIAL_PURCHASE, RENEWAL, EXPIRATION, ...
  app_user_id         uuid,                      -- = profiles.id
  store               text,                      -- APP_STORE | PLAY_STORE | ...
  environment         text,                      -- PRODUCTION | SANDBOX
  period_type         text,                      -- TRIAL | NORMAL | INTRO
  is_trial_conversion boolean not null default false,
  price               numeric,
  currency            text,
  event_at            timestamptz,               -- when it happened at RevenueCat
  created_at          timestamptz not null default now()
);

create index if not exists sub_events_at_idx   on public.subscription_events (event_at);
create index if not exists sub_events_type_idx on public.subscription_events (type, event_at);

alter table public.subscription_events enable row level security;
-- deliberately NO policies: service_role only.

select 'subscription_events ready (service-role only, RLS on with no policies)' as note;
