-- BlockView — Supabase schema
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.
-- Creates per-user tables for favorites, follows and notes, with Row-Level
-- Security so each user only sees their own data, plus free-tier limit
-- enforcement (5 saves / 3 follows) that Pro users bypass.

-- ---------- profiles (one row per user, holds the plan) ----------
create table if not exists public.profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  plan          text not null default 'free' check (plan in ('free','pro')),
  avatar_url    text,                                  -- small compressed data-URL avatar
  notifications boolean not null default false,        -- push-notifications preference
  saved_filter  jsonb,                                 -- user's default search filter
  theme         text not null default 'light',         -- color mode: 'light' | 'dark'
  created_at    timestamptz not null default now()
);
-- for existing databases, add the new columns if missing:
alter table public.profiles add column if not exists avatar_url    text;
alter table public.profiles add column if not exists notifications boolean not null default false;
alter table public.profiles add column if not exists saved_filter  jsonb;
alter table public.profiles add column if not exists theme         text not null default 'light';

-- auto-create a profile when a new user signs up
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, plan) values (new.id, 'free')
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ---------- favorites ----------
create table if not exists public.favorites (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  listing_id text not null,
  created_at timestamptz not null default now(),
  unique (user_id, listing_id)
);

-- ---------- follows (subscribed buildings) ----------
create table if not exists public.follows (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  building_id text not null,
  created_at  timestamptz not null default now(),
  unique (user_id, building_id)
);

-- ---------- notes ----------
create table if not exists public.notes (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users (id) on delete cascade,
  listing_id text not null,
  body       text not null default '',
  updated_at timestamptz not null default now(),
  unique (user_id, listing_id)
);

-- ---------- Row-Level Security ----------
alter table public.profiles  enable row level security;
alter table public.favorites enable row level security;
alter table public.follows   enable row level security;
alter table public.notes     enable row level security;

-- profiles: user reads/updates only their own row
create policy "profiles_self_select" on public.profiles for select using (auth.uid() = id);
create policy "profiles_self_update" on public.profiles for update using (auth.uid() = id);

-- favorites / follows / notes: full CRUD only on own rows
create policy "favorites_owner" on public.favorites for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "follows_owner" on public.follows for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "notes_owner" on public.notes for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------- Free-tier limits (server-enforced, Pro bypasses) ----------
-- Change these two numbers to change the free tier.
create or replace function public.enforce_limits()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  user_plan text;
  cnt int;
  max_fav  int := 3;   -- free saves
  max_foll int := 0;   -- free follows (0 = follow is Pro-only)
begin
  select plan into user_plan from public.profiles where id = new.user_id;
  if user_plan is null then user_plan := 'free'; end if;

  if user_plan <> 'pro' then
    if tg_table_name = 'favorites' then
      select count(*) into cnt from public.favorites where user_id = new.user_id;
      if cnt >= max_fav then
        raise exception 'FREE_LIMIT_FAVORITES' using errcode = 'P0001';
      end if;
    elsif tg_table_name = 'follows' then
      select count(*) into cnt from public.follows where user_id = new.user_id;
      if cnt >= max_foll then
        raise exception 'FREE_LIMIT_FOLLOWS' using errcode = 'P0001';
      end if;
    end if;
  end if;
  return new;
end; $$;

drop trigger if exists limit_favorites on public.favorites;
create trigger limit_favorites before insert on public.favorites
  for each row execute procedure public.enforce_limits();

drop trigger if exists limit_follows on public.follows;
create trigger limit_follows before insert on public.follows
  for each row execute procedure public.enforce_limits();
